CREATE TABLE plaid_categories (
    category         VARCHAR(255) PRIMARY KEY,
    category_type    VARCHAR(8)   NOT NULL,
    primary_category VARCHAR(255)
);

INSERT INTO plaid_categories (category, category_type, primary_category) VALUES
-- Primary categories
('INCOME',                    'PRIMARY',  NULL),
('LOAN_DISBURSEMENTS',        'PRIMARY',  NULL),
('LOAN_PAYMENTS',             'PRIMARY',  NULL),
('TRANSFER_IN',               'PRIMARY',  NULL),
('TRANSFER_OUT',              'PRIMARY',  NULL),
('BANK_FEES',                 'PRIMARY',  NULL),
('ENTERTAINMENT',             'PRIMARY',  NULL),
('FOOD_AND_DRINK',            'PRIMARY',  NULL),
('GENERAL_MERCHANDISE',       'PRIMARY',  NULL),
('HOME_IMPROVEMENT',          'PRIMARY',  NULL),
('MEDICAL',                   'PRIMARY',  NULL),
('PERSONAL_CARE',             'PRIMARY',  NULL),
('GENERAL_SERVICES',          'PRIMARY',  NULL),
('GOVERNMENT_AND_NON_PROFIT', 'PRIMARY',  NULL),
('TRANSPORTATION',            'PRIMARY',  NULL),
('TRAVEL',                    'PRIMARY',  NULL),
('RENT_AND_UTILITIES',        'PRIMARY',  NULL),
('OTHER',                     'PRIMARY',  NULL),

-- INCOME
('INCOME_CHILD_SUPPORT',           'DETAILED', 'INCOME'),
('INCOME_CONTRACTOR',              'DETAILED', 'INCOME'),
('INCOME_DIVIDENDS',               'DETAILED', 'INCOME'),
('INCOME_GIG_ECONOMY',             'DETAILED', 'INCOME'),
('INCOME_INTEREST_EARNED',         'DETAILED', 'INCOME'),
('INCOME_LONG_TERM_DISABILITY',    'DETAILED', 'INCOME'),
('INCOME_MILITARY',                'DETAILED', 'INCOME'),
('INCOME_RENTAL',                  'DETAILED', 'INCOME'),
('INCOME_RETIREMENT_PENSION',      'DETAILED', 'INCOME'),
('INCOME_SALARY',                  'DETAILED', 'INCOME'),
('INCOME_TAX_REFUND',              'DETAILED', 'INCOME'),
('INCOME_UNEMPLOYMENT',            'DETAILED', 'INCOME'),
('INCOME_OTHER',                   'DETAILED', 'INCOME'),

-- LOAN_DISBURSEMENTS
('LOAN_DISBURSEMENTS_AUTO',               'DETAILED', 'LOAN_DISBURSEMENTS'),
('LOAN_DISBURSEMENTS_CASH_ADVANCES',      'DETAILED', 'LOAN_DISBURSEMENTS'),
('LOAN_DISBURSEMENTS_EWA',                'DETAILED', 'LOAN_DISBURSEMENTS'),
('LOAN_DISBURSEMENTS_MORTGAGE',           'DETAILED', 'LOAN_DISBURSEMENTS'),
('LOAN_DISBURSEMENTS_PERSONAL',           'DETAILED', 'LOAN_DISBURSEMENTS'),
('LOAN_DISBURSEMENTS_STUDENT',            'DETAILED', 'LOAN_DISBURSEMENTS'),
('LOAN_DISBURSEMENTS_OTHER_DISBURSEMENT', 'DETAILED', 'LOAN_DISBURSEMENTS'),

-- LOAN_PAYMENTS
('LOAN_PAYMENTS_BNPL',                   'DETAILED', 'LOAN_PAYMENTS'),
('LOAN_PAYMENTS_CAR_PAYMENT',            'DETAILED', 'LOAN_PAYMENTS'),
('LOAN_PAYMENTS_CASH_ADVANCES',          'DETAILED', 'LOAN_PAYMENTS'),
('LOAN_PAYMENTS_CREDIT_CARD_PAYMENT',    'DETAILED', 'LOAN_PAYMENTS'),
('LOAN_PAYMENTS_EWA',                    'DETAILED', 'LOAN_PAYMENTS'),
('LOAN_PAYMENTS_MORTGAGE_PAYMENT',       'DETAILED', 'LOAN_PAYMENTS'),
('LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT',  'DETAILED', 'LOAN_PAYMENTS'),
('LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT',   'DETAILED', 'LOAN_PAYMENTS'),
('LOAN_PAYMENTS_OTHER_PAYMENT',          'DETAILED', 'LOAN_PAYMENTS'),

-- TRANSFER_IN
('TRANSFER_IN_ACCOUNT_TRANSFER',               'DETAILED', 'TRANSFER_IN'),
('TRANSFER_IN_DEPOSIT',                        'DETAILED', 'TRANSFER_IN'),
('TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS','DETAILED', 'TRANSFER_IN'),
('TRANSFER_IN_SAVINGS',                        'DETAILED', 'TRANSFER_IN'),
('TRANSFER_IN_TRANSFER_IN_FROM_APPS',          'DETAILED', 'TRANSFER_IN'),
('TRANSFER_IN_WIRE',                           'DETAILED', 'TRANSFER_IN'),
('TRANSFER_IN_CASH_ADVANCES_AND_LOANS',        'DETAILED', 'TRANSFER_IN'),
('TRANSFER_IN_OTHER_TRANSFER_IN',              'DETAILED', 'TRANSFER_IN'),

-- TRANSFER_OUT
('TRANSFER_OUT_ACCOUNT_TRANSFER',                'DETAILED', 'TRANSFER_OUT'),
('TRANSFER_OUT_CRYPTO',                          'DETAILED', 'TRANSFER_OUT'),
('TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS', 'DETAILED', 'TRANSFER_OUT'),
('TRANSFER_OUT_SAVINGS',                         'DETAILED', 'TRANSFER_OUT'),
('TRANSFER_OUT_TRANSFER_OUT_FROM_APPS',          'DETAILED', 'TRANSFER_OUT'),
('TRANSFER_OUT_WIRE',                            'DETAILED', 'TRANSFER_OUT'),
('TRANSFER_OUT_WITHDRAWAL',                      'DETAILED', 'TRANSFER_OUT'),
('TRANSFER_OUT_OTHER_TRANSFER_OUT',              'DETAILED', 'TRANSFER_OUT'),

-- BANK_FEES
('BANK_FEES_ATM_FEES',              'DETAILED', 'BANK_FEES'),
('BANK_FEES_INSUFFICIENT_FUNDS',    'DETAILED', 'BANK_FEES'),
('BANK_FEES_INTEREST_CHARGE',       'DETAILED', 'BANK_FEES'),
('BANK_FEES_FOREIGN_TRANSACTION_FEES','DETAILED','BANK_FEES'),
('BANK_FEES_OVERDRAFT_FEES',        'DETAILED', 'BANK_FEES'),
('BANK_FEES_LATE_FEES',             'DETAILED', 'BANK_FEES'),
('BANK_FEES_CASH_ADVANCE',          'DETAILED', 'BANK_FEES'),
('BANK_FEES_OTHER_BANK_FEES',       'DETAILED', 'BANK_FEES'),

-- ENTERTAINMENT
('ENTERTAINMENT_CASINOS_AND_GAMBLING',                         'DETAILED', 'ENTERTAINMENT'),
('ENTERTAINMENT_MUSIC_AND_AUDIO',                              'DETAILED', 'ENTERTAINMENT'),
('ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS',  'DETAILED', 'ENTERTAINMENT'),
('ENTERTAINMENT_TV_AND_MOVIES',                                'DETAILED', 'ENTERTAINMENT'),
('ENTERTAINMENT_VIDEO_GAMES',                                  'DETAILED', 'ENTERTAINMENT'),
('ENTERTAINMENT_OTHER_ENTERTAINMENT',                          'DETAILED', 'ENTERTAINMENT'),

-- FOOD_AND_DRINK
('FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR',   'DETAILED', 'FOOD_AND_DRINK'),
('FOOD_AND_DRINK_COFFEE',                 'DETAILED', 'FOOD_AND_DRINK'),
('FOOD_AND_DRINK_FAST_FOOD',              'DETAILED', 'FOOD_AND_DRINK'),
('FOOD_AND_DRINK_GROCERIES',              'DETAILED', 'FOOD_AND_DRINK'),
('FOOD_AND_DRINK_RESTAURANT',             'DETAILED', 'FOOD_AND_DRINK'),
('FOOD_AND_DRINK_VENDING_MACHINES',       'DETAILED', 'FOOD_AND_DRINK'),
('FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK',   'DETAILED', 'FOOD_AND_DRINK'),

-- GENERAL_MERCHANDISE
('GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS',      'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES',       'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_CONVENIENCE_STORES',             'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_DEPARTMENT_STORES',              'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_DISCOUNT_STORES',                'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_ELECTRONICS',                    'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES',            'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_OFFICE_SUPPLIES',                'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_ONLINE_MARKETPLACES',            'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_PET_SUPPLIES',                   'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_SPORTING_GOODS',                 'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_SUPERSTORES',                    'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_TOBACCO_AND_VAPE',               'DETAILED', 'GENERAL_MERCHANDISE'),
('GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',      'DETAILED', 'GENERAL_MERCHANDISE'),

-- HOME_IMPROVEMENT
('HOME_IMPROVEMENT_FURNITURE',           'DETAILED', 'HOME_IMPROVEMENT'),
('HOME_IMPROVEMENT_HARDWARE',            'DETAILED', 'HOME_IMPROVEMENT'),
('HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE','DETAILED','HOME_IMPROVEMENT'),
('HOME_IMPROVEMENT_SECURITY',            'DETAILED', 'HOME_IMPROVEMENT'),
('HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT','DETAILED','HOME_IMPROVEMENT'),

-- MEDICAL
('MEDICAL_DENTAL_CARE',               'DETAILED', 'MEDICAL'),
('MEDICAL_EYE_CARE',                  'DETAILED', 'MEDICAL'),
('MEDICAL_NURSING_CARE',              'DETAILED', 'MEDICAL'),
('MEDICAL_PHARMACIES_AND_SUPPLEMENTS','DETAILED', 'MEDICAL'),
('MEDICAL_PRIMARY_CARE',              'DETAILED', 'MEDICAL'),
('MEDICAL_VETERINARY_SERVICES',       'DETAILED', 'MEDICAL'),
('MEDICAL_OTHER_MEDICAL',             'DETAILED', 'MEDICAL'),

-- PERSONAL_CARE
('PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS', 'DETAILED', 'PERSONAL_CARE'),
('PERSONAL_CARE_HAIR_AND_BEAUTY',          'DETAILED', 'PERSONAL_CARE'),
('PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING', 'DETAILED', 'PERSONAL_CARE'),
('PERSONAL_CARE_OTHER_PERSONAL_CARE',      'DETAILED', 'PERSONAL_CARE'),

-- GENERAL_SERVICES
('GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING', 'DETAILED', 'GENERAL_SERVICES'),
('GENERAL_SERVICES_AUTOMOTIVE',                        'DETAILED', 'GENERAL_SERVICES'),
('GENERAL_SERVICES_CHILDCARE',                         'DETAILED', 'GENERAL_SERVICES'),
('GENERAL_SERVICES_CONSULTING_AND_LEGAL',              'DETAILED', 'GENERAL_SERVICES'),
('GENERAL_SERVICES_EDUCATION',                         'DETAILED', 'GENERAL_SERVICES'),
('GENERAL_SERVICES_INSURANCE',                         'DETAILED', 'GENERAL_SERVICES'),
('GENERAL_SERVICES_POSTAGE_AND_SHIPPING',              'DETAILED', 'GENERAL_SERVICES'),
('GENERAL_SERVICES_STORAGE',                           'DETAILED', 'GENERAL_SERVICES'),
('GENERAL_SERVICES_OTHER_GENERAL_SERVICES',            'DETAILED', 'GENERAL_SERVICES'),

-- GOVERNMENT_AND_NON_PROFIT
('GOVERNMENT_AND_NON_PROFIT_DONATIONS',                        'DETAILED', 'GOVERNMENT_AND_NON_PROFIT'),
('GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES','DETAILED','GOVERNMENT_AND_NON_PROFIT'),
('GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT',                      'DETAILED', 'GOVERNMENT_AND_NON_PROFIT'),
('GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT',  'DETAILED', 'GOVERNMENT_AND_NON_PROFIT'),

-- TRANSPORTATION
('TRANSPORTATION_BIKES_AND_SCOOTERS', 'DETAILED', 'TRANSPORTATION'),
('TRANSPORTATION_GAS',                'DETAILED', 'TRANSPORTATION'),
('TRANSPORTATION_PARKING',            'DETAILED', 'TRANSPORTATION'),
('TRANSPORTATION_PUBLIC_TRANSIT',     'DETAILED', 'TRANSPORTATION'),
('TRANSPORTATION_TAXIS_AND_RIDE_SHARES','DETAILED','TRANSPORTATION'),
('TRANSPORTATION_TOLLS',              'DETAILED', 'TRANSPORTATION'),
('TRANSPORTATION_OTHER_TRANSPORTATION','DETAILED', 'TRANSPORTATION'),

-- TRAVEL
('TRAVEL_FLIGHTS',      'DETAILED', 'TRAVEL'),
('TRAVEL_LODGING',      'DETAILED', 'TRAVEL'),
('TRAVEL_RENTAL_CARS',  'DETAILED', 'TRAVEL'),
('TRAVEL_OTHER_TRAVEL', 'DETAILED', 'TRAVEL'),

-- RENT_AND_UTILITIES
('RENT_AND_UTILITIES_GAS_AND_ELECTRICITY',     'DETAILED', 'RENT_AND_UTILITIES'),
('RENT_AND_UTILITIES_INTERNET_AND_CABLE',      'DETAILED', 'RENT_AND_UTILITIES'),
('RENT_AND_UTILITIES_RENT',                    'DETAILED', 'RENT_AND_UTILITIES'),
('RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT','DETAILED','RENT_AND_UTILITIES'),
('RENT_AND_UTILITIES_TELEPHONE',               'DETAILED', 'RENT_AND_UTILITIES'),
('RENT_AND_UTILITIES_WATER',                   'DETAILED', 'RENT_AND_UTILITIES'),
('RENT_AND_UTILITIES_OTHER_UTILITIES',         'DETAILED', 'RENT_AND_UTILITIES'),

-- OTHER
('OTHER_OTHER', 'DETAILED', 'OTHER');
